shop/shop/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import sales.views as sales
import accounts.views as accounts
from django.contrib.auth import views as auth_views

# error pages
handler500 = "sales.views.custom_500"
handler404 = "sales.views.custom_404"

urlpatterns = [
    url(r'^$', sales.index, name='index'),
    # account service pages
    url(r'^login/?$', accounts.login, name='login'),
    url(r'^logout/?$', auth_views.logout, {'next_page': '/'}, name='logout'),
    # also neede password_reset + password_change

    url(r'^profile/?$', accounts.profile, name='profile'),
    url(r'^profile/update/?$', accounts.update, name='profile_update'),
    url(r'^registration/?$', accounts.registration, name='registration'),

    url(r'^show/(?P<id>\d+)/?$', sales.show, name='show'),
    url(r'^add/(?P<id>\d+)/?$', sales.add, name='add'),
    url(r'^delete/(?P<id>\d+)/?$', sales.delete, name='delete'),
    url(r'^cart/?$', sales.cart, name='cart'),
    url(r'^confirm/?$', sales.confirm, name='confirm'),
    url(r'^orders/?$', sales.orders, name='orders'),
    url(r'^order/(?P<id>\d+)/?$', sales.order, name='order'),

    # admin interface
    url(r'^admin/', admin.site.urls),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
]

shop/accounts/models.py
from django.db import models
from django.contrib.auth.models import User


class Customer(models.Model):
    """Customer's account"""
    user = models.OneToOneField(User)
    patronymic = models.CharField(max_length=255, verbose_name='patronymic', help_text="user's patronymic")
    phone = models.CharField(max_length=20, verbose_name='phone', help_text="user's phone number")

    def __str__(self):
        return self.user.username

    class Meta:
        ordering = ['id']
        verbose_name = 'Customer'
        verbose_name_plural = 'Customers'


class Delivery(models.Model):
    """Customers' delivery info"""
    customer =  models.ForeignKey(Customer, verbose_name='customer', on_delete=models.CASCADE)
    address = models.TextField(verbose_name='address', help_text='delivery address')
    created = models.DateTimeField(auto_now_add=True, editable=False)

    def __str__(self):
        return "{} delivery".format(self.customer)

    def short(self):
        if len(self.address) > 64:
            return self.address[:64] + "..."
        return self.address

    class Meta:
        ordering = ['address']
        verbose_name = 'Delivery'
        verbose_name_plural = 'Deliveries'

shop/sales/models.py
from django.db import models
from django.conf import settings
from shop import addons
import os


class Category(models.Model):
    """Products' category"""
    name = models.CharField(max_length=200, verbose_name='name', help_text='category name', unique=True)
    desc = models.TextField(verbose_name='description', help_text='category description')
    modified = models.DateTimeField(auto_now=True, editable=False)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'


class Product(models.Model):
    """Products class"""
    name = models.CharField(max_length=200, verbose_name='name', help_text='product name', db_index=True)
    category = models.ForeignKey(Category, verbose_name='category', help_text="product's category")
    price = models.FloatField(verbose_name='price', help_text="product's price", db_index=True)
    image = models.ImageField(upload_to='images/', verbose_name='image', help_text="product's image")
    desc = models.TextField(verbose_name='description', help_text="product's description")
    modified = models.DateTimeField(auto_now=True, editable=False)
    created = models.DateTimeField(auto_now_add=True, editable=False)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']
        verbose_name = 'Product'
        verbose_name_plural = 'Products'


class Order(models.Model):
    """Orders info"""
    STATUSES = (
        (0, 'preparation'),
        (1, 'sent'),
        (2, 'received'),
    )
    customer = models.ForeignKey('accounts.Customer', verbose_name='customer')
    product = models.ManyToManyField(Product, verbose_name='Product', through='ProductSet', blank=True)
    desc = models.TextField(verbose_name='description', help_text="order's description", blank=True)
    status = models.PositiveIntegerField(verbose_name='status', help_text="order's status", choices=STATUSES, default=0)
    modified = models.DateTimeField(auto_now=True, editable=False, db_index=True)
    created = models.DateTimeField(auto_now_add=True, editable=False, db_index=True)

    def __str__(self):
        return "Order-{}".format(self.id)

    class Meta:
        ordering = ['-modified', '-created']
        verbose_name = 'Order'
        verbose_name_plural = 'Orders'

    def total(self):
        s = 0
        for ps in self.productset_set.all():
            s += ps.total()
        return s


class ProductSet(models.Model):
    """A set products in the order"""
    product = models.ForeignKey(Product, verbose_name='Product')
    order = models.ForeignKey(Order, verbose_name='Order')
    number = models.PositiveIntegerField(verbose_name='number', default=1)

    def __str__(self):
        return "ProductSet-{}".format(self.id)

    class Meta:
        ordering = ['id']
        verbose_name = 'ProductSet'
        verbose_name_plural = 'ProductSets'

    def total(self):
        return self.product.price * self.number

shop/accounts/forms.py
from django import forms
from django.contrib.auth import password_validation
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
import re

# hard phone number template: +xx (xxx) xxxx-xx-xx
PHONE_RG = re.compile(r'^\+\d{,2}\s?\(\d{3}\)\s?\d{3}-?\d{2}-?\d{2}$', re.IGNORECASE)


def phone_validation(value):
    if not PHONE_RG.match(value):
        raise ValidationError("incorrect phone number, please use format +xx (xxx) xxxx-xx-xx")


class Profile(forms.Form):
    first_name = forms.CharField(
        max_length=255,
        required=True,
        widget=forms.TextInput(attrs={'placeholder': 'First name', 'class': 'form-control'}),
    )
    middle_name = forms.CharField(
        max_length=255,
        required=True,
        widget=forms.TextInput(attrs={'placeholder': 'Middle name', 'class': 'form-control'}),
    )
    last_name = forms.CharField(
        max_length=255,
        required=True,
        widget=forms.TextInput(attrs={'placeholder': 'Last name', 'class': 'form-control'}),
    )
    email = forms.EmailField(
        max_length=255,
        required=True,
        widget=forms.TextInput(attrs={'placeholder': 'Email', 'class': 'form-control'}),
    )
    phone = forms.CharField(
        validators=[phone_validation],
        max_length=20,
        required=True,
        widget=forms.TextInput(attrs={'placeholder': '+xx (xxx) xxxx-xx-xx', 'class': 'form-control'}),
    )


class Registration(forms.Form):
    first_name = forms.CharField(
        max_length=255,
        required=True,
        widget=forms.TextInput(attrs={'placeholder': 'First name', 'class': 'form-control'}),
    )
    middle_name = forms.CharField(
        max_length=255,
        required=True,
        widget=forms.TextInput(attrs={'placeholder': 'Middle name', 'class': 'form-control'}),
    )
    last_name = forms.CharField(
        max_length=255,
        required=True,
        widget=forms.TextInput(attrs={'placeholder': 'Last name', 'class': 'form-control'}),
    )
    email = forms.EmailField(
        max_length=255,
        required=True,
        widget=forms.TextInput(attrs={'placeholder': 'Email', 'class': 'form-control'}),
    )
    phone = forms.CharField(
        validators=[phone_validation],
        max_length=20,
        required=True,
        widget=forms.TextInput(attrs={'placeholder': '+xx (xxx) xxxx-xx-xx', 'class': 'form-control'}),
    )
    password = forms.CharField(
        max_length=64,
        required=True,
        validators=[password_validation.validate_password],
        widget=forms.PasswordInput(attrs={'placeholder': 'Password', 'class': 'form-control'}),
    )
    password_confirm = forms.CharField(
        max_length=64,
        required=True,
        widget=forms.PasswordInput(attrs={'placeholder': 'Password confirm', 'class': 'form-control'}),
    )

    def clean_password_confirm(self):
        if self.cleaned_data.get('password') != self.cleaned_data.get('password_confirm'):
            raise ValidationError('Passwords mismatched')
        return self.cleaned_data.get('password_confirm')

    def clean_email(self):
        email = self.cleaned_data.get('email')
        try:
            User.objects.get(email=email)
        except User.DoesNotExist:
            pass
        else:
            raise ValidationError('User is already exists')
        return email

shop/accounts/views.py
from accounts.forms import Profile, Registration
from accounts.models import Customer
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.db import transaction
from django.http import Http404
from django.shortcuts import render, redirect
from django.views.decorators.csrf import csrf_protect
from shop import addons
from shop.cart import Cart
import logging


LOGGER = logging.getLogger(__name__)


@addons.secure
def login(request):
    # use custom wrapper method to control addons.secure
    if request.user.is_authenticated():
        return redirect(reverse('index'))
    return auth_views.login(request)


@addons.secure
@login_required
def profile(request):
    if not hasattr(request.user, 'customer'):
        LOGGER.error("user is not related with a customer")
        raise Http404("user is not related with a customer")
    cart = Cart(request)
    context = {
        'customer': request.user.customer,
        'cart_count': cart.count(),
        'customer': request.user.customer,
    }
    return render(request, 'accounts/profile.html', context)


@addons.secure
@login_required
@csrf_protect
def update(request):
    """User profile update"""
    if not hasattr(request.user, 'customer'):
        raise Http404("user is not related with a customer")
    customer = request.user.customer
    if request.method == 'POST':
        form = Profile(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            with transaction.atomic():
                user = customer.user
                user.first_name = data['first_name']
                user.last_name = data['last_name']
                user.email = user.username = data['email']
                user.save()
                customer.patronymic = data['middle_name']
                customer.phone = data['phone']
                customer.save()
            return redirect(reverse('profile'))
    else:
        data = {
            'first_name': customer.user.first_name,
            'middle_name': customer.patronymic,
            'last_name': customer.user.last_name,
            'email': customer.user.email,
            'phone': customer.phone,
        }
        form = Profile(data)
    cart = Cart(request)
    context = {
        'customer': request.user.customer,
        'form': form,
        'cart_count': cart.count(),
    }
    return render(request, 'accounts/update.html', context)


@addons.secure
@csrf_protect
def registration(request):
    """User registration"""
    if request.user.is_authenticated():
        return redirect(reverse('index'))
    if request.method == 'POST':
        form = Registration(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            with transaction.atomic():
                user = User(
                    username=data['email'],
                    first_name=data['first_name'],
                    last_name=data['last_name'],
                    email=data['email'],
                )
                user.set_password(data['password'])
                user.save()
                customer = Customer(
                    user=user,
                    phone=data['phone'],
                    patronymic=data['middle_name'],
                )
                customer.save()
            return redirect(reverse('profile'))
    else:
        form = Registration()
    cart = Cart(request)
    context = {
        'form': form,
        'cart_count': cart.count(),
    }
    return render(request, 'accounts/create.html', context)

shop/accounts/templates/accounts/create.html
{% extends "base/blank.html" %}
{% block title %}eShop - registration{% endblock %}
{% block header %}User registration{% endblock %}
{% block cart %}({{ cart_count }}){% endblock %}

{% block content %}
<div class="container">
  <div class="row">
    <form action="" method="post">
      {% csrf_token %}
      <div class="form-group row">
        <label for="id_first_name" class="col-sm-2 form-control-label">First name</label>
        <div class="col-sm-4">
          {{ form.first_name }}
          <span class="help-inline">{{ form.first_name.errors }}</span>
        </div>
      </div>

      <div class="form-group row">
        <label for="id_first_name" class="col-sm-2 form-control-label">Middle name</label>
        <div class="col-sm-4">
          {{ form.middle_name }}
          <span class="help-inline">{{ form.middle_name.errors }}</span>
        </div>
      </div>

      <div class="form-group row">
        <label for="id_first_name" class="col-sm-2 form-control-label">Last name</label>
        <div class="col-sm-4">
          {{ form.last_name }}
          <span class="help-inline">{{ form.last_name.errors }}</span>
        </div>
      </div>

      <div class="form-group row">
        <label for="id_first_name" class="col-sm-2 form-control-label">Email</label>
        <div class="col-sm-4">
          {{ form.email }}
          <span class="help-inline">{{ form.email.errors }}</span>
        </div>
      </div>

      <div class="form-group row">
        <label for="id_first_name" class="col-sm-2 form-control-label">Phone number</label>
        <div class="col-sm-4">
          {{ form.phone }}
          <span class="help-inline">{{ form.phone.errors }}</span>
        </div>
      </div>

      <div class="form-group row">
        <label for="id_first_name" class="col-sm-2 form-control-label">Password</label>
        <div class="col-sm-4">
          {{ form.password }}
          <span class="help-inline">{{ form.password.errors }}</span>
        </div>
      </div>

      <div class="form-group row">
        <label for="id_first_name" class="col-sm-2 form-control-label">Password confirm</label>
        <div class="col-sm-4">
          {{ form.password_confirm }}
          <span class="help-inline">{{ form.password_confirm.errors }}</span>
        </div>
      </div>

      <button type="submit" class="btn btn-primary">Submit</button>
    </form>
  </div>
</div>
<hr>
{% endblock content %}

shop/accounts/templates/accounts/profile.html
{% extends "base/blank.html" %}
{% block title %}eShop{% endblock %}
{% block header %}Profile{% endblock %}
{% block cart %}({{ cart_count }}){% endblock %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-sm-2">
      <b>First name</b>
    </div>
    <div class="col-sm-10">
      {{ customer.user.first_name }}
    </div>
  </div>
  <div class="row">
    <div class="col-sm-2">
      <b>Middle name</b>
    </div>
    <div class="col-sm-10">
      {{ customer.patronymic }}
    </div>
  </div>
  <div class="row">
    <div class="col-sm-2">
      <b>Last name</b>
    </div>
    <div class="col-sm-10">
      {{ customer.user.last_name }}
    </div>
  </div>
  <div class="row">
    <div class="col-sm-2">
      <b>Email</b>
    </div>
    <div class="col-sm-10">
      {{ customer.user.email }}
    </div>
  </div>
  <div class="row">
    <div class="col-sm-2">
      <b>Phone number</b>
    </div>
    <div class="col-sm-10">
      {{ customer.phone }}
    </div>
  </div>
</div>
<hr>
<p>
  <a href="{% url 'profile_update' %}" class="btn btn-primary">Change</a>
  {% if customer.order_set.count %}
    <a href="{% url 'orders' %}" class="btn btn-info">Orders</a>
  {% endif %}
</p>

{% endblock content %}

shop/accounts/templates/accounts/update.html
{% extends "base/blank.html" %}
{% block title %}eShop - profile update{% endblock %}
{% block header %}Profile update{% endblock %}
{% block cart %}({{ cart_count }}){% endblock %}

{% block content %}
<div class="container">
  <div class="row">
    {# {{ form.errors }} #}
    <form action="" method="post">
      {% csrf_token %}
      <div class="form-group row">
        <label for="id_first_name" class="col-sm-2 form-control-label">First name</label>
        <div class="col-sm-4">
          {{ form.first_name }}
          <span class="help-inline">{{ form.first_name.errors }}</span>
        </div>
      </div>

      <div class="form-group row">
        <label for="id_first_name" class="col-sm-2 form-control-label">Middle name</label>
        <div class="col-sm-4">
          {{ form.middle_name }}
          <span class="help-inline">{{ form.middle_name.errors }}</span>
        </div>
      </div>

      <div class="form-group row">
        <label for="id_first_name" class="col-sm-2 form-control-label">Last name</label>
        <div class="col-sm-4">
          {{ form.last_name }}
          <span class="help-inline">{{ form.last_name.errors }}</span>
        </div>
      </div>

      <div class="form-group row">
        <label for="id_first_name" class="col-sm-2 form-control-label">Email</label>
        <div class="col-sm-4">
          {{ form.email }}
          <span class="help-inline">{{ form.email.errors }}</span>
        </div>
      </div>

      <div class="form-group row">
        <label for="id_first_name" class="col-sm-2 form-control-label">Phone number</label>
        <div class="col-sm-4">
          {{ form.phone }}
          <span class="help-inline">{{ form.phone.errors }}</span>
        </div>
      </div>

      <button type="submit" class="btn btn-primary">Submit</button>
    </form>
  </div>
</div>
<hr>
{% endblock content %}