shop/shop/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import sales.views as sales
import accounts.views as accounts
from django.contrib.auth import views as auth_views

# error pages
handler500 = "sales.views.custom_500"
handler404 = "sales.views.custom_404"

urlpatterns = [
    url(r'^$', sales.index, name='index'),
    # account service pages
    url(r'^login/?$', accounts.login, name='login'),
    url(r'^logout/?$', auth_views.logout, {'next_page': '/'}, name='logout'),
    # also neede password_reset + password_change

    url(r'^profile/?$', accounts.profile, name='profile'),
    url(r'^profile/update/?$', accounts.update, name='profile_update'),
    url(r'^registration/?$', accounts.registration, name='registration'),

    url(r'^show/(?P<id>\d+)/?$', sales.show, name='show'),
    url(r'^add/(?P<id>\d+)/?$', sales.add, name='add'),
    url(r'^delete/(?P<id>\d+)/?$', sales.delete, name='delete'),
    url(r'^cart/?$', sales.cart, name='cart'),
    url(r'^confirm/?$', sales.confirm, name='confirm'),
    url(r'^orders/?$', sales.orders, name='orders'),
    url(r'^order/(?P<id>\d+)/?$', sales.order, name='order'),

    # admin interface
    url(r'^admin/', admin.site.urls),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
]

shop/sales/models.py
from django.db import models
from django.conf import settings
from shop import addons
import os


class Category(models.Model):
    """Products' category"""
    name = models.CharField(max_length=200, verbose_name='name', help_text='category name', unique=True)
    desc = models.TextField(verbose_name='description', help_text='category description')
    modified = models.DateTimeField(auto_now=True, editable=False)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'


class Product(models.Model):
    """Products class"""
    name = models.CharField(max_length=200, verbose_name='name', help_text='product name', db_index=True)
    category = models.ForeignKey(Category, verbose_name='category', help_text="product's category")
    price = models.FloatField(verbose_name='price', help_text="product's price", db_index=True)
    image = models.ImageField(upload_to='images/', verbose_name='image', help_text="product's image")
    desc = models.TextField(verbose_name='description', help_text="product's description")
    modified = models.DateTimeField(auto_now=True, editable=False)
    created = models.DateTimeField(auto_now_add=True, editable=False)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']
        verbose_name = 'Product'
        verbose_name_plural = 'Products'


class Order(models.Model):
    """Orders info"""
    STATUSES = (
        (0, 'preparation'),
        (1, 'sent'),
        (2, 'received'),
    )
    customer = models.ForeignKey('accounts.Customer', verbose_name='customer')
    product = models.ManyToManyField(Product, verbose_name='Product', through='ProductSet', blank=True)
    desc = models.TextField(verbose_name='description', help_text="order's description", blank=True)
    status = models.PositiveIntegerField(verbose_name='status', help_text="order's status", choices=STATUSES, default=0)
    modified = models.DateTimeField(auto_now=True, editable=False, db_index=True)
    created = models.DateTimeField(auto_now_add=True, editable=False, db_index=True)

    def __str__(self):
        return "Order-{}".format(self.id)

    class Meta:
        ordering = ['-modified', '-created']
        verbose_name = 'Order'
        verbose_name_plural = 'Orders'

    def total(self):
        s = 0
        for ps in self.productset_set.all():
            s += ps.total()
        return s


class ProductSet(models.Model):
    """A set products in the order"""
    product = models.ForeignKey(Product, verbose_name='Product')
    order = models.ForeignKey(Order, verbose_name='Order')
    number = models.PositiveIntegerField(verbose_name='number', default=1)

    def __str__(self):
        return "ProductSet-{}".format(self.id)

    class Meta:
        ordering = ['id']
        verbose_name = 'ProductSet'
        verbose_name_plural = 'ProductSets'

    def total(self):
        return self.product.price * self.number

shop/sales/forms.py
from django import forms
from django.core.exceptions import ValidationError


class OrderForm(forms.Form):
    product = forms.IntegerField(
        min_value=1,
        required=True,
        widget=forms.HiddenInput(),
    )
    count = forms.IntegerField(
        min_value=1,
        max_value=1000000,
        required=True,
        widget=forms.NumberInput(attrs={'class': 'form-control'}),
    )


class DeliveryForm(forms.Form):
    new = forms.CharField(
        max_length=4096,
        required=False,
        widget=forms.TextInput(attrs={'placeholder': 'New shipping address', 'class': 'form-control'}),
    )
    existed = forms.ChoiceField(
        required=False,
        widget=forms.Select(attrs={'class': 'form-control'}),
    )
    comment = forms.CharField(
        required=False,
        widget=forms.Textarea(attrs={'class': 'form-control', 'rows': '2'}),
    )

    def set_choises(self, customer):
        deliveries = [(0, 'Set new address')]
        deliveries += [(d.id, d.short()) for d in customer.delivery_set.all()]
        self.fields['existed'].choices = deliveries

    def clean_existed(self):
        if self.cleaned_data.get('existed') == '0' and (not self.cleaned_data.get('new')):
            raise ValidationError('Enter new shipping address')
        return self.cleaned_data.get('existed')

shop/sales/views.py
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.urlresolvers import reverse
from django.db import transaction
from django.forms import formset_factory
from django.http import Http404
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.csrf import csrf_protect
from sales.forms import OrderForm, DeliveryForm
from sales.models import Category, Product, Order, ProductSet
from accounts.models import Delivery
from shop import addons
from shop.cart import Cart
import logging


LOGGER = logging.getLogger(__name__)


@addons.nosecure
def index(request):
    categories = Category.objects.all().order_by('name')
    # filter params: page, category, name
    category = None
    params = {'cat_url': [], 'page_url': []}
    products = Product.objects.all().order_by('-modified')

    # text search filter
    search = request.GET.get('name', '')
    if search:
        products = products.filter(name__icontains=request.GET['name'])
        params['cat_url'].append('name=' + request.GET['name'])
        params['page_url'].append('name=' + request.GET['name'])

    # categories filter
    try:
        if request.GET.get('cat'):
            category = Category.objects.get(pk=int(request.GET['cat']))
            products = products.filter(category=category)
            params['page_url'].append('cat=' + str(category.id))
    except (ValueError, Category.DoesNotExist) as err:
        LOGGER.error(err)

    # pagination filter
    paginator = Paginator(products, settings.PRODUCTS_ON_PAGE)
    page = request.GET.get('page', 1)
    try:
        products = paginator.page(page)
    except PageNotAnInteger:
        page = 1
        products = paginator.page(page)
    except EmptyPage:
        page = paginator.num_pages
        products = paginator.page(page)

    params['cat_url'].append('page=' + str(page))

    cart = Cart(request)
    context = {
        'categories': categories,
        'request': request,
        'params': params,
        'products': products,
        'search': search,
        'category': category,
        'cart_count': cart.count(),
    }
    return render(request, 'sales/index.html', context)


def custom_500(request):
    # some custom actions
    return render(request, '500.html', {"MEDIA_URL", settings.MEDIA_URL})


def custom_404(request):
    # some custom actions
    return render(request, '404.html')


@addons.nosecure
def show(request, id):
    """Product card page"""
    product = get_object_or_404(Product, pk=id)
    cart = Cart(request)
    context = {
        'product': product,
        'in_cart': cart.has(product),
        'cart_count': cart.count(),
    }
    return render(request, 'sales/show.html', context)


@addons.nosecure
def add(request, id):
    """It adds the product to the Cart"""
    product = get_object_or_404(Product, pk=id)
    cart = Cart(request)
    cart.add_or_update(product, 1)
    context = {
        'product': product,
        'in_cart': cart.has(product),
        'cart_count': cart.count(),
    }
    return cart.set(render(request, 'sales/show.html', context))


@addons.nosecure
def delete(request, id):
    """It removes the product from the Cart"""
    product = get_object_or_404(Product, pk=id)
    cart = Cart(request)
    cart.delete(product)
    return cart.set(redirect(reverse('cart')))


@addons.secure
@csrf_protect
def cart(request):
    """It showes customer's cart
    and allows to change products numbers.
    """
    cart = Cart(request)
    products = cart.get()
    products_ids = {p.id: p for p in products}
    OrderFormSet = formset_factory(OrderForm, extra=0)
    if request.method == 'POST':
        formset = OrderFormSet(request.POST)
        if formset.is_valid() and formset.has_changed():
            for cd in formset.cleaned_data:
                product = get_object_or_404(Product, pk=cd['product'])
                cart.add_or_update(product, cd['count'])
    else:
        data = [{'product': p.id, 'count': c} for p, c in products.items()]
        formset = OrderFormSet(initial=data)
    for form in formset:
        form.product_info = products_ids[int(form.hidden_fields()[0].value())]
    context = {
        'products': products,
        'formset': formset,
        'cart_count': cart.count(),
        'total': cart.total(),
    }
    return cart.set(render(request, 'sales/cart.html', context))


@addons.secure
@login_required
@csrf_protect
def confirm(request):
    """It confirms a customer's order
    and sets delivery address
    """
    if not hasattr(request.user, 'customer'):
        raise Http404("user is not related with a customer")
    customer = request.user.customer
    cart = Cart(request)
    if cart.is_empty():
        # empty cart can't approve any order
        return redirect(reverse('index'))
    products = []
    try:
        for product, count in cart.get().items():
            product.count = count
            product.total = round(product.price * int(count), 2)
            products.append(product)
    except (ValueError,) as err:
        raise Http404(err)
    if request.method == 'POST':
        form = DeliveryForm(request.POST)
        form.set_choises(customer)
        if form.is_valid():
            data = form.cleaned_data
            with transaction.atomic():
                if data['new']:
                    # create new delivery address
                    delivery = Delivery(
                        customer=customer,
                        address=data['new'],
                    )
                    delivery.save()
                else:
                    # use existed address
                    delivery = get_object_or_404(Delivery, pk=data['existed'])
                order = Order(
                    customer=customer,
                    desc=data['comment'],
                )
                order.save()
                for product in products:
                    ProductSet.objects.create(
                        product=product,
                        order=order,
                        number=product.count,
                    )
            return cart.clean(redirect(reverse('order', args=[order.id])))
    else:
        form = DeliveryForm()
        form.set_choises(customer)
    context = {
        'products': products,
        'cart_count': cart.count(),
        'total': cart.total(),
        'form': form,
    }
    return render(request, 'sales/confirm.html', context)


@addons.secure
@login_required
def orders(request):
    if not hasattr(request.user, 'customer'):
        raise Http404("user is not related with a customer")
    cart = Cart(request)
    orders = request.user.customer.order_set.all()
    context = {
        'orders': orders,
        'cart_count': cart.count(),
    }
    return render(request, 'sales/orders.html', context)


@addons.secure
@login_required
def order(request, id):
    if not hasattr(request.user, 'customer'):
        raise Http404("user is not related with a customer")
    cart = Cart(request)
    order = get_object_or_404(Order, pk=id, customer=request.user.customer)
    context = {
        'order': order,
        'cart_count': cart.count(),
    }
    return render(request, 'sales/order.html', context)

shop/sales/templates/sales/cart.html
{% extends "base/blank.html" %}
{% block title %}eShop - Cart{% endblock %}
{% block header %}Cart{% endblock %}
{% block cart %}({{ cart_count }}){% endblock %}

{% block content %}
  <div class="container">
    <div class="row">
      {% if cart_count %}
        {% if formset.total_error_count %}
          <p><b>Please enter a correct number value.</b></p>
        {% endif %}
        <form action="" method="post">
          {% csrf_token %}
          {{ formset.management_form.as_p }}
          <table class="table table-striped">
            <thead class="thead-inverse">
              <tr>
                <th>Product</th>
                <th>Price</th>
                <th width="150px">Number</th>
                <th width="150px"></th>
              </tr>
            </thead>
            <tbody>
              {% for form in formset %}
                <tr>
                  <td>{{ form.product_info.name }}</td>
                  <td>{{ form.product_info.price|floatformat:2 }}</td>
                  <td>
                    {{ form.product }}
                    {{ form.count }}
                  </td>
                  <td><a href="{% url 'delete' form.product_info.id %}" class="btn btn-danger">Delete</a></td>
                </tr>
              {% endfor %}
            </tbody>
            <tfoot>
              <tr>
                <th>Total:</th>
                <th>{{ total }}</th>
                <th></th>
                <th></th>
              </tr>
            </tfoot>
          </table>
          <hr>
          <a href="{% url 'confirm' %}" class="btn btn-primary">Checkout</a>
          <button type="submit" class="btn btn-success">Update</button>
        </form>
      {% else %}
        <p>You have no any products in the Cart.</p>
        <p><a href="{% url 'index' %}" class="btn btn-primary">Continue the shopping</a></p>
      {% endif %}
    </div>
  </div>
{% endblock content %}

shop/sales/templates/sales/confirm.html
{% extends "base/blank.html" %}
{% block title %}eShop - Order confirm{% endblock %}
{% block header %}Order confirm{% endblock %}
{% block cart %}({{ cart_count }}){% endblock %}

{% block content %}
  <div class="container">
    <div class="row">
      <table class="table table-striped">
        <thead class="thead-inverse">
          <tr>
            <th>Product</th>
            <th>Price</th>
            <th width="150px">Number</th>
            <th width="150px">Sum</th>
          </tr>
        </thead>
        <tbody>
          {% for product in products %}
            <tr>
              <td>{{ product.name }}</td>
              <td>{{ product.price|floatformat:2 }}</td>
              <td>{{ product.count }}</td>
              <td>{{ product.total }}</td>
            </tr>
          {% endfor %}
        </tbody>
        <tfoot>
          <tr>
            <th>Total:</th>
            <th></th>
            <th></th>
            <th>{{ total }}</th>
          </tr>
        </tfoot>
      </table>
    </div>
    <div class="row">
      <form action="" method="post">
        {% csrf_token %}
        <div class="form-group row">
          <label for="id_existed" class="col-sm-3 form-control-label">Addreses</label>
          <div class="col-sm-6">
            {{ form.existed }}
            <span class="help-inline">{{ form.existed.errors }}</span>
          </div>
        </div>
        <div class="form-group row">
          <label for="id_new" class="col-sm-3 form-control-label">New shipping address</label>
          <div class="col-sm-6">
            {{ form.new }}
            <span class="help-inline">{{ form.new.errors }}</span>
          </div>
        </div>
        <div class="form-group row">
          <label for="id_comment" class="col-sm-3 form-control-label">Comment</label>
          <div class="col-sm-6">
            {{ form.comment }}
          </div>
        </div>
        <a href="{% url 'cart' %}" class="btn btn-warning">Back</a>
        <button type="submit" class="btn btn-success">Confirm</button>
      </form>
    </div>
  </div>
{% endblock content %}

shop/sales/templates/sales/index.html
{% extends "base/basis.html" %}
{% block title %}eShop{% endblock %}
{% block header %}eShop is not a real shop{% endblock %}
{% block search %}{{ search }}{% endblock %}
{% block cart %}({{ cart_count }}){% endblock %}
{% block categories %}
  <li><a href="/?{{ params.cat_url|join:"&" }}">All</a></li>
  {% for cat in categories %}
    {# cache should be used here #}
    <li><a href="/?{{ params.cat_url|join:"&" }}&cat={{ cat.id }}">{{ cat.name }} ({{ cat.product_set.count }})</a></li>
  {% endfor %}
{% endblock %}

{% block content %}
{% if category %}
  <h2>{{ category.name }}</h2>
{% endif %}
{% if search %}
  <p><b>Filtered by text</b>: &lsquo;{{ search }}&rsquo;</p>
{% endif %}

{% if products.has_other_pages %}
  <nav>
  <ul class="pagination">
    {% if products.has_previous %}
    <li class="page-item">
      <a class="page-link" href="/?{{ params.page_url|join:"&" }}&page={{ products.previous_page_number }}" aria-label="Previous">
        <span aria-hidden="true">&laquo;</span>
        <span class="sr-only">Previous</span>
      </a>
    </li>
    {% endif %}
    {% for p in products.paginator.page_range %}
      {% if products.number == p %}
        <li class="page-item active">
          <span class="page-link">{{ p }} <span class="sr-only">(current)</span></span>
        </li>
      {% else %}
        <li class="page-item">
          <a class="page-link" href="/?{{ params.page_url|join:"&" }}&page={{ p }}">{{ p }}</a>
        </li>
      {% endif %}
    {% endfor %}
    {% if products.has_next %}
    <li class="page-item">
      <a class="page-link" href="/?{{ params.page_url|join:"&" }}&page={{ products.next_page_number }}" aria-label="Next">
        <span aria-hidden="true">&raquo;</span>
        <span class="sr-only">Next</span>
      </a>
    </li>
    {% endif %}
  </ul>
</nav>
{% endif %}

{% if products.object_list %}
  <div class="album text-muted">
    <div class="container">
      <div class="row">
      {% for product in products %}
        <div class="card">
          <a href="{% url 'show' product.id %}" title="{{ product.name }}">
            <img class="media-object" src="{{ product.image.url }}" height="100px">
          </a>
          <p class="card-text">{{ product.name|safe }}</p>
          <p>{{ product.price|floatformat:2 }} rub.</p>
          <p><a href="{% url 'show' product.id %}" title="{{ product.name }}" class="btn btn-primary">View</a></p>
        </div>
      {% endfor %}
      </div>
    </div>
  </div>
{% else %}
  <p><i>Not found any products.</i></p>
{% endif %}
{% endblock content %}

shop/sales/templates/sales/order.html
{% extends "base/blank.html" %}
{% block title %}eShop - Orders #{{ order.id }}{% endblock %}
{% block header %}Order #{{ order.id }}{% endblock %}
{% block cart %}({{ cart_count }}){% endblock %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-sm-2">
      <b>Number</b>
    </div>
    <div class="col-sm-10">
      {{ order.id }}
    </div>
  </div>
  <div class="row">
    <div class="col-sm-2">
      <b>Status</b>
    </div>
    <div class="col-sm-10">
      {{ order.get_status_display }}
    </div>
  </div>
  <div class="row">
    <div class="col-sm-2">
      <b>Last updated</b>
    </div>
    <div class="col-sm-10">
      {{ order.modified }}
    </div>
  </div>
  <div class="row">
    <hr>
    <table class="table table-hover">
      <thead class="thead-inverse">
        <tr>
          <th>Product</th>
          <th>Price</th>
          <th>Number</th>
          <th width="150px">Total</th>
        </tr>
      </thead>
      <tbody>
      {% for ps in order.productset_set.all %}
        <tr>
          <td>{{ ps.product.name }}</td>
          <td>{{ ps.product.price }}</td>
          <td>{{ ps.number }}</td>
          <td>{{ ps.total }}</td>
        </tr>
      {% endfor %}
      </tbody>
      <tfoot>
        <tr>
          <th>Total</th>
          <th></th>
          <th></th>
          <th>{{ order.total }}</th>
        </tr>
      </tfoot>
    </table>
  </div>
</div>
{% endblock content %}

shop/sales/templates/sales/orders.html
{% extends "base/blank.html" %}
{% block title %}eShop - Orders{% endblock %}
{% block header %}Orders{% endblock %}
{% block cart %}({{ cart_count }}){% endblock %}

{% block content %}
<div class="container">
  <div class="row">
    <table class="table table-hover">
      <thead class="thead-inverse">
        <tr>
          <th>#</th>
          <th>Status</th>
          <th>Last update date</th>
          <th width="150px">Total</th>
          <th width="150px"></th>
        </tr>
      </thead>
      <tbody>
        {% for order in orders %}
          <tr>
            <td>{{ order.id }}</td>
            <td>{{ order.get_status_display }}</td>
            <td>{{ order.modified }}</td>
            <td>{{ order.total|floatformat:2 }}</td>
            <td><a href="{% url 'order' order.id %}" class="btn btn-info">View</a></td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
{% endblock content %}

shop/sales/templates/sales/show.html
{% extends "base/blank.html" %}
{% block title %}eShop - {{ product.name }}{% endblock %}
{% block header %}{{ product.name }}{% endblock %}
{% block cart %}({{ cart_count }}){% endblock %}

{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-sm-6">
        <img class="media-object" src="{{ product.image.url }}" width="100%">
      </div>
      <div class="col-sm-6">
        {{ product.desc|safe }}
        <hr>
        {% if in_cart %}
          <a href="{% url 'cart' %}" class="btn btn-primary">Checkout the Order</a>
        {% else %}
          <a href="{% url 'add' product.id %}" class="btn btn-primary">Add to Cart</a>
        {% endif %}
      </div>
    </div>
  </div>
{% endblock content %}